[build]
buildCommand = "echo 'Building WaveSens services'"

[deploy]
startCommand = "echo 'This is a monorepo. Deploy individual services from their directories.'"

# Service configurations for Railway
[services.backend]
source = "backend/"
buildCommand = "echo 'Building backend'"

[services.frontend]
source = "frontend/"
buildCommand = "echo 'Building frontend'"

[services.news_analyzer]
source = "news_analyzer/"
buildCommand = "echo 'Building news analyzer'"

[services.signal_extractor]
source = "signal_extractor/"
buildCommand = "echo 'Building signal extractor'"

[services.experiment_manager]
source = "experiment_manager/"
buildCommand = "echo 'Building experiment manager'"